apiVersion: apps/v1
kind: Deployment
metadata:
  name: mincraft-app
  labels:
    app: mincraft-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mincraft-app
  template:
    metadata:
      labels:
        app: mincraft-app
    spec:
      containers:
      - name: mincraft-app
        image: 849277819322.dkr.ecr.ca-central-1.amazonaws.com/jjtech-demo:replaceImageTag
        ports:
        - containerPort: 8080
